FROM httpd:2.2.32

LABEL io.cloudunit="" \
      io.cloudunit.type=server \
      io.cloudunit.name.service=apache \
      io.cloudunit.name.display="Apache $HTTPD_VERSION" \
      io.cloudunit.version=$HTTPD_VERSION \
