FROM redis:3.2

LABEL io.cloudunit="" \
      io.cloudunit.type=module \
      io.cloudunit.name.service=redis \
      io.cloudunit.name.display="Redis $REDIS_VERSION" \
      io.cloudunit.version=$REDIS_VERSION
