FROM postgres:9.4

LABEL io.cloudunit="" \
      io.cloudunit.type=module \
      io.cloudunit.name.service=postgresql \
      io.cloudunit.name.display="PostgreSQL $PG_MAJOR" \
      io.cloudunit.version=$PG_MAJOR \
      io.cloudunit.variables="{\"POSTGRES_USER\": \"USER\", \"POSTGRES_PASSWORD\": \"PASSWORD\", \"POSTGRES_DB\": \"NAME\"}"
