FROM mongo:2.6.12

LABEL io.cloudunit="" \
      io.cloudunit.type=module \
      io.cloudunit.name.service=mongo \
      io.cloudunit.name.display="Mongo $MONGO_VERSION" \
      io.cloudunit.version=$MONGO_VERSION
