FROM mongo:2.6.12

ENV MONGO_MAJOR "2.6"

LABEL io.cloudunit="" \
      io.cloudunit.type=module \
      io.cloudunit.name.service=mongo \
      io.cloudunit.name.display="Mongo $MONGO_MAJOR" \
      io.cloudunit.version=$MONGO_VERSION
