#!/bin/bash

# file: cloudunit-completion
# cloudunit parameter-completion

_Completion ()   #  By convention, the function name
{                 #+ starts with an underscore.
	local cur
	# Pointer to current completion word.
	# By convention, it's named "cur" but this isn't strictly necessary.

	COMPREPLY=()   # Array variable storing the possible completions.
	cur=${COMP_WORDS[COMP_CWORD]}

	case "$cur" in
		*)
			COMPREPLY=( $( compgen -W '-v -h reset restart' -- $cur ) );;
		-*)
			COMPREPLY=( $( compgen -W '-v -h' -- $cur ) );;
			#   Generate the completion matches and load them into $COMPREPLY array.
		r*)
			COMPREPLY=( $( compgen -W 'reset restart' -- $cur ) );;
	esac

	return 0
}

complete -F _Completion -o filenames cloudunit
#        ^^ ^^^^^^^^^^^^  Invokes the function _UseGetOpt-2.
