#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:           cu-platform
# Required-Start:     docker
# Required-Stop:      docker
# Should-Start:       cgroupfs-mount cgroup-lite
# Should-Stop:        cgroupfs-mount cgroup-lite
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  cu platform
# Description:
#  Fig launches cu platform.
### END INIT INFO

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
PLATFORM_DIR=/home/admincu/cloudunit/cu-platform

# Get lsb functions
. /lib/lsb/init-functions

if [ ! -e /vagrant ]; then
	CU_USER=admincu
else
	CU_USER=vagrant
fi

case "$1" in
	start)
#		fail_unless_root

		log_begin_msg "Starting cu-platform"
		su - $CU_USER -c "cd $PLATFORM_DIR && $PLATFORM_DIR/start-platform.sh"
		log_end_msg $?
		;;

	stop)
#		fail_unless_root
		log_begin_msg "Stopping cu-platform"
		su - $CU_USER -c "cd $PLATFORM_DIR && docker-compose stop"
		log_end_msg $?
		;;

	restart)
#		fail_unless_root
		$0 stop
		$0 start
		;;

	status)
		su - $CU_USER -c "cd $PLATFORM_DIR && docker-compose ps"
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac
