#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:           mountsshfs
# Required-Start:     networking
# Required-Stop:      networking
# Should-Start:       
# Should-Stop:        
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  mount sshfs 
# Description:
# Mount cloudunit via sshfs.
### END INIT INFO

DISTANT_DIR=claire@192.168.1.107:/home/claire/cloudunit
ENABLE_SSHFS=false

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

# Get lsb functions
. /lib/lsb/init-functions

if [ $ENABLE_SSHFS = true ]; then
	case "$1" in
		start)
			log_begin_msg "Mounting sshfs"
			su - admincu -c "sshfs $DISTANT_DIR /home/admincu/cloudunit -o nonempty -o uid=900 -o gid=900 -o allow_root"
			log_end_msg $?
			;;

		stop)
			log_begin_msg "Unmounting sshfs"
			umount $DISTANT_DIR
			log_end_msg $?
			;;

		restart)
			$0 stop
			$0 start
			;;

		*)
			echo "Usage: $0 {start|stop|restart}"
			exit 1
			;;
	esac
else
	echo "Sshfs is disabled. Set ENABLE_SSHFS to true to enable it."
fi
