FROM rabbitmq:3.6

LABEL io.cloudunit="" \
      io.cloudunit.type=module \
      io.cloudunit.name.service=rabbitmq \
      io.cloudunit.name.display="RabbitMQ $RABBITMQ_VERSION" \
      io.cloudunit.version=$RABBITMQ_VERSION
