FROM elasticsearch:2.4

LABEL io.cloudunit="" \
      io.cloudunit.type=server \
      io.cloudunit.name.service=elastic \
      io.cloudunit.name.display="Elasticsearch $ELASTICSEARCH_VERSION" \
      io.cloudunit.version=$ELASTICSEARCH_VERSION
